# DS4B 101-P: PYTHON FOR DATA SCIENCE AUTOMATION ----
# Environment Setup ----

# Conda Environment Setup Instructions ----
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
# 
#    conda env create -f 000_environment_setup/01_conda_environment.yml
#    conda env update --file 000_environment_setup/01_conda_environment.yml --prune
#    conda env export --name ds4b_101p > envname.yml
#    conda env remove --name ds4b_101p
#    conda env list

name: ds4b_101p
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.1
  - pip
  - pip:
      # Core Data
      - numpy==1.21.6
      - pandas==1.2.2

      # R Data
      - plydata==0.4.3
      - siuba==0.0.24
      - datatable

      # Visualization
      - matplotlib==3.3.4
      - plotnine==0.7.1
      - mizani==0.7.2
      - plotly==4.14.3
      - altair==4.1.0

      # EDA
      - pandas-profiling
      - ppscore==1.2.0
      - pyjanitor==0.20.14

      # Modeling & Machine Learning
      - statsmodels
      #- nltk==3.5
      - h2o==3.32.0.3
      - pycaret==2.3.10
      - scikit-learn==0.23.2
      # - xgboost==0.90
      # - lightgbm==3.1.1
      # - catboost==0.24.4
      #- sklearn-pandas==2.0.4
      #- scikit-misc==0.1.4

      # Time Series
      #- sktime==0.5.3
      #- pmdarima==1.8.1
      #- tsfresh==0.17.0

      # Scalability & Automation
      # - dask==2.30.0
      # - dask-ml==1.8.0
      # - dask-xgboost==0.1.11
      #- zict==1.0.0
      #- joblib==1.0.1

      # API
      #- fastapi==0.63.0
      #- uvicorn==0.13.4

      # Database
      #- sqlalchemy==1.4.7

      # Excel
      #- xlsxwriter==1.3.7
      #- openpyxl

      # Jupyter
      #- jupyterlab==3.0.13
      #- jupyterlab-server==2.4.0
      #- jupyter-packaging==0.7.12
      #- jupyter-server==1.15.4 # Solves ImportError: cannot import name 'get_version_info' from 'jupyter_packaging'
      #- ipywidgets==7.6.3
      #- ipympl==0.7.0
      #- jupytext
      #- papermill==2.3.3
      #- pandoc

      # Apps
      # - streamlit==0.80.0

      # Terminal Formatting
      #- rich

      # Extending Pandas
      #- pandas_flavor==0.2.0

      # R users
      #- radian
      #- jedi==0.17.2